namespace CRM.Models.Business
{
    /// <summary>
    /// Instancias de negocio
    /// </summary>
    public class Business
    {
        public Actividades actividades;
        public Actividades2 actividades2;
        public ActividadesContacto actividadescontacto;
        public ActividadesContactoDetalle actividadescontactodetalle;
        public Archivos archivos;
        public ArchivosBitacora archivosbitacora;
        public Area area;
        public AsaeWebEventos asaewebeventos;
        public AsaeWebUsuariosEventos asaewebusuarioseventos;
        public Aviso aviso;
        public Bitacora bitacora;
        public BitacoraUsuarios bitacorausuarios;
        public BitacoraUsuariosDetalle bitacorausuariosdetalle;
        public Clasificacion clasificacion;
        public ClasificacionRolesContactos clasificacionrolescontactos;
        public ClassSubClass classsubclass;
        public ClassSubClassEtiquetas classsubclassetiquetas;
        public CodigoPostal codigopostal;
        public CompartirContactos compartircontactos;
        public CompartirEmpresa compartirempresa;
        public CompartirOportunidades compartiroportunidades;
        public Configuracion configuracion;
        public ContactoRol contactorol;
        public Contactos contactos;
        public ContactosActividades contactosactividades;
        public ContactosDetalle contactosdetalle;
        public ContactosEmpresas contactosempresas;
        public Colonias colonias;
        public CP cp;
        public DocumentosASAE documentosasae;
        public DocumentosASAEHistorico documentosasaehistorico;
        public DocumentosASAESubClasificaciones documentosasaesubclasificaciones;
        public DocumentosASAETipoArchivo documentosasaetipoarchivo;
        public DocumentosASAEUsuarios documentosasaeusuarios;
        public Empresas empresas;
        public EmpresasDetalle empresasdetalle;
        public EmpresasDirecciones empresasdirecciones;
        public EmpresasProveedores empresasproveedores;
        public EmpresasUsuarios empresasusuarios;
        public Estados estados;
        public Escalacion escalacion;
        public Estadisticas estadisticas;
        public EstadoOportunidad estadooportunidad;
        public EtapasBitacora etapasbitacora;
        public EtapasOportunidad etapasoportunidad;
        public FechaVencimientoCambios fechavencimientocambios;
        public Marketing marketing;
        public MarketingContactos marketingcontactos;
        public MarketingCorreo marketingcorreo;
        public MarketingCorreoPlantillas marketingcorreoplantillas;
        public MarketingRecordatorios marketingrecordatorios;
        public MarketingSeguimiento marketingseguimiento;
        public Menu menu;
        public Metricas metricas;
        public Moneda moneda;
        public MultiRepositorio multirepositorio;
        public Oportunidades oportunidades;
        public OportunidadesActividades oportunidadesactividades;
        public OportunidadesEmpresasContactosUsuarios oecu;
        public OportunidadesImportes oportunidadesimportes;
        public OportunidadesResponsables oportunidadesresponsables;
        public OportunidadesUsuarios oportunidadesusuarios;
        public Poblaciones poblaciones;
        public Paises paises;
        public Roles roles;
        public SubClasificacion subclasificacion;
        public Tareas tareas;
        public TareasUsuariosContactosEmpresas tuce;
        public TipoPersona tipopersona;
        public UDN udn;
        public UsuarioConfiguracion usuarioconfiguracion;
        public Usuarios usuarios;
        public UsuariosEmpresasOportunidades ueo;
        public UsuariosRoles usuariosroles;

        public Business()
        {
            actividades = new Actividades();
            actividades2 = new Actividades2();
            actividadescontacto = new ActividadesContacto();
            actividadescontactodetalle = new ActividadesContactoDetalle();
            archivos = new Archivos();
            archivosbitacora = new ArchivosBitacora();
            area = new Area();
            asaewebeventos = new AsaeWebEventos();
            asaewebusuarioseventos = new AsaeWebUsuariosEventos();
            aviso = new Aviso();
            bitacora = new Bitacora();
            bitacorausuarios = new BitacoraUsuarios();
            bitacorausuariosdetalle = new BitacoraUsuariosDetalle();
            clasificacion = new Clasificacion();
            clasificacionrolescontactos = new ClasificacionRolesContactos();
            classsubclass = new ClassSubClass();
            classsubclassetiquetas = new ClassSubClassEtiquetas();
            codigopostal = new CodigoPostal();
            compartircontactos = new CompartirContactos();
            compartirempresa = new CompartirEmpresa();
            compartiroportunidades = new CompartirOportunidades();
            configuracion = new Configuracion();
            contactorol = new ContactoRol();
            contactos = new Contactos();
            contactosactividades = new ContactosActividades();
            contactosdetalle = new ContactosDetalle();
            contactosempresas = new ContactosEmpresas();
            colonias = new Colonias();
            cp = new CP();
            documentosasae = new DocumentosASAE();
            documentosasaehistorico = new DocumentosASAEHistorico();
            documentosasaesubclasificaciones = new DocumentosASAESubClasificaciones();
            documentosasaetipoarchivo = new DocumentosASAETipoArchivo();
            documentosasaeusuarios = new DocumentosASAEUsuarios();
            empresas = new Empresas();
            empresasdetalle = new EmpresasDetalle();
            empresasdirecciones = new EmpresasDirecciones();
            empresasproveedores = new EmpresasProveedores();
            empresasusuarios = new EmpresasUsuarios();
            escalacion = new Escalacion();
            estadisticas = new Estadisticas();
            estados = new Estados();
            estadooportunidad = new EstadoOportunidad();
            etapasbitacora = new EtapasBitacora();
            etapasoportunidad = new EtapasOportunidad();
            fechavencimientocambios = new FechaVencimientoCambios();
            marketing = new Marketing();
            marketingcontactos = new MarketingContactos();
            marketingcorreo = new MarketingCorreo();
            marketingcorreoplantillas = new MarketingCorreoPlantillas();
            marketingrecordatorios = new MarketingRecordatorios();
            marketingseguimiento = new MarketingSeguimiento();
            menu = new Menu();
            metricas = new Metricas();
            moneda = new Moneda();
            multirepositorio = new MultiRepositorio();
            oportunidades = new Oportunidades();
            oportunidadesactividades = new OportunidadesActividades();
            oecu = new OportunidadesEmpresasContactosUsuarios();
            oportunidadesimportes = new OportunidadesImportes();
            oportunidadesresponsables = new OportunidadesResponsables();
            oportunidadesusuarios = new OportunidadesUsuarios();
            poblaciones = new Poblaciones();
            paises = new Paises();
            roles = new Roles();
            subclasificacion = new SubClasificacion();
            tareas = new Tareas();
            tuce = new TareasUsuariosContactosEmpresas();
            tipopersona = new TipoPersona();
            udn = new UDN();
            usuarioconfiguracion = new UsuarioConfiguracion();
            usuarios = new Usuarios();
            ueo = new UsuariosEmpresasOportunidades();
            usuariosroles = new UsuariosRoles();
        }
    }
}
